# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Sapling"
license = "MIT"
licenselink = "https://github.com/KeyofSamuel/sapling-hugo-theme/blob/master/LICENSE"
description = "A Hugo theme specifically for daycare and similar service industry companies"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Samuel A. Campbell"
  homepage = "https://keyofsamuel.com"
